modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="rail_smelting"
version="1.2.0"
displayName="Rail Smelting"
displayURL="https://github.com/Grey-Wind/RailSmelting"
logoFile="logo.png"
credits="https://github.com/Grey-Wind/RailSmelting"
authors="Grey Wind"
description="A modpack that add some recipes about the rail smelting."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rail_smelting]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rail_smelting]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



