modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="rail_firing"
version="1.0.0"
displayName="Rail Firing"
credits="https://github.com/Grey-Wind/RailFiring"
displayURL="https://github.com/Grey-Wind/RailFiring"
authors="Grey Wind"
description="A modpack that add some recipes about the rail firing."

[[dependencies.rail_firing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




