modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="rail_smelting"
version="1.0.0"
displayName="Rail Smelting"
displayURL="https://github.com/Grey-Wind/RailSmelting"
credits="https://github.com/Grey-Wind/RailSmelting"
authors="Grey Wind"
description="A modpack that add some recipes about the rail smelting."

[[dependencies.rail_smelting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




